---
# Simple NGINX install + basic page for Ubuntu (corrected)
# - Fixed handlers to avoid invalid 'listen' attribute on a block
# - Keeps config test before reload
- name: Install and configure nginx on Ubuntu
  hosts: all
  become: yes
  vars:
    nginx_listen_port: 80
    server_name: "{{ ansible_fqdn | default(inventory_hostname) }}"
    index_content: |
      <html>
      <head><title>Welcome</title></head>
      <body>
        <h1>Welcome to {{ server_name }}</h1>
        <p>Managed by Ansible.</p>
      </body>
      </html>

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure web root exists
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Deploy a simple index.html
      copy:
        dest: /var/www/html/index.html
        content: "{{ index_content }}"
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Test and reload nginx

    - name: (Optional) Ensure default nginx site config uses correct listen port
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*listen\s+[0-9]+'
        line: "    listen {{ nginx_listen_port }} default_server;"
        backrefs: yes
      notify: Test and reload nginx

  handlers:
    - name: Test and reload nginx
      block:
        - name: Test nginx configuration
          command: nginx -t
          register: nginx_test
          changed_when: false
          failed_when: nginx_test.rc != 0

        - name: Reload nginx
          service:
            name: nginx
            state: reloaded
